name: google_sign_in_all_platforms_android
description: Android implementation of the google_sign_in_all_platforms plugin
version: 0.0.1
homepage: https://github.com/vishnuagbly/google_sign_in_all_platforms/tree/main/google_sign_in_all_platforms_android

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: google_sign_in_all_platforms
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsAndroid
      ios:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsAndroid
      web:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsAndroid
        fileName: google_sign_in_all_platforms_android.dart

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  google_sign_in_all_platforms_interface: ^0.0.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
