name: google_sign_in_all_platforms_ios
description: iOS implementation of the google_sign_in_all_platforms plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: google_sign_in_all_platforms
    platforms:
      ios:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsIOS

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_all_platforms_platform_interface:
    path: ../google_sign_in_all_platforms_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
