version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/google_sign_in_all_platforms_windows"
    schedule:
      interval: "daily"