// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFBGKfm5jRHkKoMQyeRoP9jyit-3rp34',
    appId: '1:292705536169:web:4052a270c1481aedfa81b8',
    messagingSenderId: '292705536169',
    projectId: 'gsap-example-app',
    authDomain: 'gsap-example-app.firebaseapp.com',
    storageBucket: 'gsap-example-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC34QZiadwUX2vdJbhNvM2FnhJL7W7SjQ',
    appId: '1:292705536169:android:4eb07ca393cf5bd9fa81b8',
    messagingSenderId: '292705536169',
    projectId: 'gsap-example-app',
    storageBucket: 'gsap-example-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33Otj1L0NZHYXw2_wqZ5QdEn5Bc7_s0Q',
    appId: '1:292705536169:ios:63d87f0b0fcf90dafa81b8',
    messagingSenderId: '292705536169',
    projectId: 'gsap-example-app',
    storageBucket: 'gsap-example-app.appspot.com',
    iosBundleId: 'com.vishnuworld.example',
  );
}
