name: google_sign_in_all_platforms_web
description: Web implementation of the google_sign_in_all_platforms plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: google_sign_in_all_platforms
    platforms:
      web:
        pluginClass: GoogleSignInAllPlatformsWeb
        fileName: google_sign_in_all_platforms_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_sign_in_all_platforms_platform_interface:
    path: ../google_sign_in_all_platforms_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
