name: google_sign_in_all_platforms_interface
description: A common platform.dart interface for the google_sign_in_all_platforms plugin.
version: 0.0.5
homepage: https://github.com/vishnuagbly/google_sign_in_all_platforms

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  plugin_platform_interface: ^2.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
