name: google_sign_in_all_platforms_macos
description: MacOS implementation of the google_sign_in_all_platforms plugin
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: google_sign_in_all_platforms
    platforms:
      macos:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsMacOS
      windows:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsMacOS
      linux:
        pluginClass: GoogleSignInAllPlatformsPlugin
        dartPluginClass: GoogleSignInAllPlatformsMacOS

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_all_platforms_interface: ^0.0.1
  googleapis_auth: ^1.4.1
  http: ^1.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
